# Site settings
# Site title
title: Eexpedition

# Site description
description: Comning soon

# Site background
background: "images/back.jpg"

# Site logo
logo: "images/logo.png"

# Countdown clock
# (This can be commented out if not required.)
#countdown:
  # format: "2013-09-25 16:00:00 +0800"
#  launch_date: 2025-01-01
  # %d, %H, %M, %S available
#  format: "%d days, %H hours, %M minutes, %S seconds"

# Mailing list subscription
# (This can be commented out if not required.)
#subscribe:
#  action: "/thank-you"

# Social media links
# (This can be commented out if not required.)
social:
  facebook: "Eexpedition-703399100080342/?view_public_for=703399100080342"
#  twitter: "#"
#  google: "#"
  instagram: "eexpedition.in/"
#  pinterest: "#"
#  snapchat: "#"
#  linkedin: "in/#"
  whatsapp: "+917829978297"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - COPYING.txt
